### ISSUE TITLE
[bug] AnimateDiff - CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by Minenblock** [light-and-ray/sd-webui-replacer#118]
<details>
<summary>Console output</summary>
```
2025-07-26 13:19:25,777 - ControlNet - INFO - unit_separate = False, style_align = False
2025-07-26 13:19:26,415 - ControlNet - INFO - Loading model: control_v11p_sd15_inpaint [ebff9138]
2025-07-26 13:19:26,798 - ControlNet - INFO - Loaded state_dict from [D:\Stuff\rp\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\models\control_v11p_sd15_inpaint.pth]
2025-07-26 13:19:26,798 - ControlNet - INFO - controlnet_default_config
2025-07-26 13:19:28,411 - ControlNet - INFO - ControlNet model control_v11p_sd15_inpaint [ebff9138](ControlModelType.ControlNet) loaded.
2025-07-26 13:19:28,412 - ControlNet - INFO - Using preprocessor: inpaint_only
2025-07-26 13:19:28,413 - ControlNet - INFO - preprocessor resolution = -1
2025-07-26 13:19:28,461 - ControlNet - INFO - ControlNet Hooked - Time = 2.6872830390930176
  0%|                                                                                           | 0/36 [00:00<?, ?it/s]2025-07-26 13:19:30,150 - ControlNet - INFO - ControlNet used torch.float16 VAE to encode torch.Size([1, 4, 64, 64]).
100%|██████████████████████████████████████████████████████████████████████████████████| 36/36 [00:15<00:00,  2.26it/s]
Restoring images resolution after ControlNet Inpainting████████████████████████████████| 36/36 [00:14<00:00,  2.48it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 36/36 [00:15<00:00,  2.35it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 36/36 [00:15<00:00,  2.48it/s]    Preparing frame in fragment 1: 1 / 24                                                       | 0/576 [00:00<?, ?it/s]
    Preparing frame in fragment 1: 2 / 24
    Preparing frame in fragment 1: 3 / 24
    Preparing frame in fragment 1: 4 / 24
    Preparing frame in fragment 1: 5 / 24
    Preparing frame in fragment 1: 6 / 24
    Preparing frame in fragment 1: 7 / 24
    Preparing frame in fragment 1: 8 / 24
    Preparing frame in fragment 1: 9 / 24
    Preparing frame in fragment 1: 10 / 24
    Preparing frame in fragment 1: 11 / 24
    Preparing frame in fragment 1: 12 / 24
    Preparing frame in fragment 1: 13 / 24
    Preparing frame in fragment 1: 14 / 24
    Preparing frame in fragment 1: 15 / 24
    Preparing frame in fragment 1: 16 / 24
    Preparing frame in fragment 1: 17 / 24
    Preparing frame in fragment 1: 18 / 24
    Preparing frame in fragment 1: 19 / 24
    Preparing frame in fragment 1: 20 / 24
    Preparing frame in fragment 1: 21 / 24
    Preparing frame in fragment 1: 22 / 24
    Preparing frame in fragment 1: 23 / 24
    Preparing frame in fragment 1: 24 / 24
inpainting fragment 1 / 16
Use cn inpaint instead of sd inpaint
2025-07-26 13:19:56,546 - AnimateDiff - INFO - AnimateDiff process start.
2025-07-26 13:19:56,546 - AnimateDiff - INFO - Loading motion module mm_sd_v15_v2.ckpt from D:\Stuff\rp\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-animatediff\model\mm_sd_v15_v2.ckpt
2025-07-26 13:19:57,099 - AnimateDiff - INFO - Guessed mm_sd_v15_v2.ckpt architecture: MotionModuleType.AnimateDiffV2
2025-07-26 13:19:59,425 - AnimateDiff - INFO - Injecting motion module mm_sd_v15_v2.ckpt into SD1.5 UNet middle block.
2025-07-26 13:19:59,425 - AnimateDiff - INFO - Injecting motion module mm_sd_v15_v2.ckpt into SD1.5 UNet input blocks.
2025-07-26 13:19:59,426 - AnimateDiff - INFO - Injecting motion module mm_sd_v15_v2.ckpt into SD1.5 UNet output blocks.
2025-07-26 13:19:59,426 - AnimateDiff - INFO - Setting DDIM alpha.
2025-07-26 13:19:59,429 - AnimateDiff - INFO - Injection finished.
2025-07-26 13:19:59,430 - AnimateDiff - INFO - AnimateDiff + ControlNet will generate 24 frames.
2025-07-26 13:19:59,480 - ControlNet - INFO - unit_separate = False, style_align = False
2025-07-26 13:19:59,963 - ControlNet - INFO - Loading model from cache: control_v11p_sd15_inpaint [ebff9138]
2025-07-26 13:19:59,963 - ControlNet - INFO - AnimateDiff + ControlNet inpaint_only receive the following parameters:
2025-07-26 13:19:59,963 - ControlNet - INFO -   batch control images: D:\Stuff\rp\Stable Diffusion\vid\jxna\TiktokDownloads\jxna.030\Videos\Replacer project - 1753527000\outputs\1753528765\fragment_1\frames
2025-07-26 13:20:01,364 - ControlNet - INFO - Using preprocessor: inpaint_only
2025-07-26 13:20:01,364 - ControlNet - INFO - preprocessor resolution = -1
100%|██████████████████████████████████████████████████████████████████████████████████| 24/24 [00:07<00:00,  3.06it/s]
2025-07-26 13:20:09,445 - ControlNet - INFO - ControlNet Hooked - Time = 9.970021724700928
2025-07-26 13:20:12,306 - AnimateDiff - INFO - Randomizing init_latent according to [1.0, 0.9375, 0.875, 0.8125, 0.75, 0.6875, 0.625, 0.5625, 0.5, 0.4375, 0.375, 0.3125, 0.25, 0.1875, 0.125, 0.0625, 0.0, -0.0625, -0.125, -0.1875, -0.25, -0.3125, -0.375, -0.4375].
  0%|                                                                                           | 0/36 [00:00<?, ?it/s]2025-07-26 13:20:12,493 - AnimateDiff - INFO - inner model forward hooked
Exception in thread MemMon:
Traceback (most recent call last):
  File "C:\Users\roblo\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
  0%|                                                                                           | 0/36 [00:00<?, ?it/s]
    self.run()
  File "D:\Stuff\rp\Stable Diffusion\stable-diffusion-webui\modules\memmon.py", line 53, in run
    free, total = self.cuda_mem_get_info()
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Stuff\rp\Stable Diffusion\stable-diffusion-webui\modules\memmon.py", line 34, in cuda_mem_get_info
    return torch.cuda.mem_get_info(index)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Stuff\rp\Stable Diffusion\stable-diffusion-webui\venv\Lib\site-packages\torch\cuda\memory.py", line 663, in mem_get_info
    return torch.cuda.cudart().cudaMemGetInfo(device)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
*** CUDA error: device-side assert triggered
*** Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
***  ***
RuntimeError: CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

    Traceback (most recent call last):
      File "D:\Stuff\rp\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-replacer\replacer\video_animatediff.py", line 166, in animatediffGenerate
        processed = processFragment(fragmentPath, initImage, gArgs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "D:\Stuff\rp\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-replacer\replacer\video_animatediff.py", line 26, in processFragment
        processed, _ = inpaint(initImage, gArgs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
      File "D:\Stuff\rp\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-replacer\replacer\inpaint.py", line 122, in inpaint
        processed = process_images(p)
                    ^^^^^^^^^^^^^^^^^
      File "D:\Stuff\rp\Stable Diffusion\stable-diffusion-webui\modules\processing.py", line 847, in process_images
        res = process_images_inner(p)
              ^^^^^^^^^^^^^^^^^^^^^^^
      File "D:\Stuff\rp\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 48, in processing_process_images_hijack
        return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "D:\Stuff\rp\Stable Diffusion\stable-diffusion-webui\modules\processing.py", line 988, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "D:\Stuff\rp\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\hook.py", line 470, in process_sample
        return process.sample_before_CN_hack(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "D:\Stuff\rp\Stable Diffusion\stable-diffusion-webui\modules\processing.py", line 1774, in sample
        samples = self.sampler.sample_img2img(self, self.init_latent, x, conditioning, unconditional_conditioning, image_conditioning=self.image_conditioning)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "D:\Stuff\rp\Stable Diffusion\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 184, in sample_img2img
        samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "D:\Stuff\rp\Stable Diffusion\stable-diffusion-webui\modules\sd_samplers_common.py", line 272, in launch_sampling
        return func()
               ^^^^^^
      File "D:\Stuff\rp\Stable Diffusion\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 184, in <lambda>
        samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "D:\Stuff\rp\Stable Diffusion\stable-diffusion-webui\venv\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "D:\Stuff\rp\Stable Diffusion\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\sampling.py", line 626, in sample_dpmpp_2m_sde
        denoised = model(x, sigmas[i] * s_in, **extra_args)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "D:\Stuff\rp\Stable Diffusion\stable-diffusion-webui\venv\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "D:\Stuff\rp\Stable Diffusion\stable-diffusion-webui\venv\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
        return forward_call(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "D:\Stuff\rp\Stable Diffusion\stable-diffusion-webui\modules\sd_samplers_cfg_denoiser.py", line 268, in forward
        x_out[a:b] = self.inner_model(x_in[a:b], sigma_in[a:b], cond=make_condition_dict(c_crossattn, image_cond_in[a:b]))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "D:\Stuff\rp\Stable Diffusion\stable-diffusion-webui\venv\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "D:\Stuff\rp\Stable Diffusion\stable-diffusion-webui\venv\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
        return forward_call(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "D:\Stuff\rp\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_infv2v.py", line 164, in mm_sd_forward
        x_in[_context], sigma_in[_context],
        ~~~~^^^^^^^^^^
    RuntimeError: CUDA error: device-side assert triggered
    Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


---
merging fragments
0it [00:00, ?it/s]
video saving
'D:\Stuff\rp\Stable Diffusion\stable-diffusion-webui\venv\Lib\site-packages\imageio_ffmpeg\binaries\ffmpeg-win-x86_64-v7.1.exe' -framerate 24 -i 'D:\Stuff\rp\Stable Diffusion\vid\...\...\...\...\Replacer project - 1753527000\outputs\1753528765\result\%5d-2856211567.png' -r 24 -i 'D:\Stuff\rp\Stable Diffusion\vid\jxna\TiktokDownloads\jxna.030\Videos\Replacer project - 1753527000\original.mp4' -map 0:v:0 -map 1:a:0? -c:v libx264 -c:a aac -vf fps=24 -profile:v main -pix_fmt yuv420p -shortest -y 'D:\Stuff\rp\Stable Diffusion\vid\...\...\...\...\Replacer project - 1753527000\outputs\1753528765\replacer_original.mp4_2856211567.mp4'
ffmpeg version 7.1-essentials_build-www.gyan.dev Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 14.2.0 (Rev1, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-dxva2 --enable-d3d11va --enable-d3d12va --enable-ffnvcodec --enable-libvpl --enable-nvdec --enable-nvenc --enable-vaapi --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      59. 39.100 / 59. 39.100
  libavcodec     61. 19.100 / 61. 19.100
  libavformat    61.  7.100 / 61.  7.100
  libavdevice    61.  3.100 / 61.  3.100
  libavfilter    10.  4.100 / 10.  4.100
  libswscale      8.  3.100 /  8.  3.100
  libswresample   5.  3.100 /  5.  3.100
  libpostproc    58.  3.100 / 58.  3.100
[image2 @ 000001bfdd8f1c80] Could find no file with path 'D:\Stuff\rp\Stable Diffusion\vid\\...\...\...\...\Replacer project - 1753527000\outputs\1753528765\result\%5d-2856211567.png' and index in the range 0-4
[in#0 @ 000001bfdd8f1880] Error opening input: No such file or directory
Error opening input file D:\Stuff\rp\Stable Diffusion\vid\...\...\...\...\Replacer project - 1753527000\outputs\1753528765\result\%5d-2856211567.png.
Error opening input files: No such file or directory
*** Error completing request
*** Arguments: ('task(igbyadhgvste5vb)', 'D:\\Stuff\\rp\\Stable Diffusion\\vid\\...\\...\\...\\...\\Replacer project - 1753527000', 24, 24, 0, 12, 1, -1, 1, 16, False, 'butterworth', 0.25, 0.25, 3, False, 'control_v11p_sd15_inpaint [ebff9138]', 1, True, 'uberRealisticPornMerge_urpmv13.safetensors [40f9701da0]', 'mm_sd_v15_v2.ckpt', 'white shirt, white top', '', 'grey shirt', '((monochrome:1.3), (deformed, distorted, disfigured:1.3), (hair), tattoo, wet, water, shadow, 3d render, cartoon, ((blurry)), duplicate, ((duplicate body parts)), (disfigured), (poorly drawn), ((missing limbs)), logo, signature, text, words, low res, boring, artifacts, bad art, gross, ugly, poor quality, low quality, poorly drawn, bad anatomy, wrong anatomy\u200b', 'None', -1, 'DPM++ 2M SDE', 'Karras', 50, 0.5, 51, 8, 1280, 'sam_vit_l_0b3195.pth', 'GroundingDINO_SwinB (938MB)', 6, 0.7, 90, 0, 512, 512, 0, False, False, 'uberRealisticPornMerge_v23Inpainting.safetensors [ac0f65dd95]', 'Random', True, 1, False, False, False, '-', -1, 0, False, True, False, ControlNetUnit(is_ui=False, input_mode=<InputMode.SIMPLE: 'simple'>, batch_images=None, output_dir='', loopback=False, enabled=False, module='none', model='None', weight=1.0, image=None, resize_mode=<ResizeMode.INNER_FIT: 'Crop and Resize'>, low_vram=False, processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0.0, guidance_end=1.0, pixel_perfect=False, control_mode=<ControlMode.BALANCED: 'Balanced'>, inpaint_crop_input_image=True, hr_option=<HiResFixOption.BOTH: 'Both'>, save_detected_map=True, advanced_weighting=None, effective_region_mask=None, pulid_mode=<PuLIDMode.FIDELITY: 'Fidelity'>, union_control_type=<ControlNetUnionControlType.UNKNOWN: 'Unknown'>, ipadapter_input=None, mask=None, batch_mask_dir=None, animatediff_batch=False, batch_modifiers=[], batch_image_files=[], batch_keyframe_idx=None), ControlNetUnit(is_ui=False, input_mode=<InputMode.SIMPLE: 'simple'>, batch_images=None, output_dir='', loopback=False, enabled=False, module='none', model='None', weight=1.0, image=None, resize_mode=<ResizeMode.INNER_FIT: 'Crop and Resize'>, low_vram=False, processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0.0, guidance_end=1.0, pixel_perfect=False, control_mode=<ControlMode.BALANCED: 'Balanced'>, inpaint_crop_input_image=True, hr_option=<HiResFixOption.BOTH: 'Both'>, save_detected_map=True, advanced_weighting=None, effective_region_mask=None, pulid_mode=<PuLIDMode.FIDELITY: 'Fidelity'>, union_control_type=<ControlNetUnionControlType.UNKNOWN: 'Unknown'>, ipadapter_input=None, mask=None, batch_mask_dir=None, animatediff_batch=False, batch_modifiers=[], batch_image_files=[], batch_keyframe_idx=None), ControlNetUnit(is_ui=False, input_mode=<InputMode.SIMPLE: 'simple'>, batch_images=None, output_dir='', loopback=False, enabled=False, module='none', model='None', weight=1.0, image=None, resize_mode=<ResizeMode.INNER_FIT: 'Crop and Resize'>, low_vram=False, processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0.0, guidance_end=1.0, pixel_perfect=False, control_mode=<ControlMode.BALANCED: 'Balanced'>, inpaint_crop_input_image=True, hr_option=<HiResFixOption.BOTH: 'Both'>, save_detected_map=True, advanced_weighting=None, effective_region_mask=None, pulid_mode=<PuLIDMode.FIDELITY: 'Fidelity'>, union_control_type=<ControlNetUnionControlType.UNKNOWN: 'Unknown'>, ipadapter_input=None, mask=None, batch_mask_dir=None, animatediff_batch=False, batch_modifiers=[], batch_image_files=[], batch_keyframe_idx=None), False, 1, 0.5, 4, 0, 0.5, 2) {}
    Traceback (most recent call last):
      File "D:\Stuff\rp\Stable Diffusion\stable-diffusion-webui\modules\call_queue.py", line 74, in f
        res = list(func(*args, **kwargs))
                   ^^^^^^^^^^^^^^^^^^^^^
      File "D:\Stuff\rp\Stable Diffusion\stable-diffusion-webui\modules\call_queue.py", line 53, in f
        res = func(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^
      File "D:\Stuff\rp\Stable Diffusion\stable-diffusion-webui\modules\call_queue.py", line 37, in f
        res = func(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^
      File "D:\Stuff\rp\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-replacer\replacer\ui\video\generation.py", line 180, in videoGenerateUI
        save_video(resultPath, target_video_fps, originalVideo, saveVideoPath, gArgs.seed)
      File "D:\Stuff\rp\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-replacer\replacer\video_tools.py", line 63, in save_video
        runFFMPEG(
      File "D:\Stuff\rp\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-replacer\replacer\video_tools.py", line 20, in runFFMPEG
        raise Exception(f'ffmpeg exited with code {rc}. See console for details')
    Exception: ffmpeg exited with code 4294967294. See console for details

---
Traceback (most recent call last):
  File "D:\Stuff\rp\Stable Diffusion\stable-diffusion-webui\venv\Lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Stuff\rp\Stable Diffusion\stable-diffusion-webui\venv\Lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Stuff\rp\Stable Diffusion\stable-diffusion-webui\venv\Lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Stuff\rp\Stable Diffusion\stable-diffusion-webui\venv\Lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Stuff\rp\Stable Diffusion\stable-diffusion-webui\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "D:\Stuff\rp\Stable Diffusion\stable-diffusion-webui\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Stuff\rp\Stable Diffusion\stable-diffusion-webui\venv\Lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "D:\Stuff\rp\Stable Diffusion\stable-diffusion-webui\modules\call_queue.py", line 91, in f
    devices.torch_gc()
  File "D:\Stuff\rp\Stable Diffusion\stable-diffusion-webui\modules\devices.py", line 81, in torch_gc
    torch.cuda.empty_cache()
  File "D:\Stuff\rp\Stable Diffusion\stable-diffusion-webui\venv\Lib\site-packages\torch\cuda\memory.py", line 159, in empty_cache
    torch._C._cuda_emptyCache()
RuntimeError: CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

<details>

**Comment by Minenblock** [comment]
> ok so the problem was my negative prompt. it was too aggresive

wait it isn't, i got this same error again. i don't know what i did. i think i changes the mask blur, Fragment length and unchecked Generate only the first fragment.

**Comment by Minenblock** [comment]
no it is not a inpainting model.

**Comment by Minenblock** [comment]
> Also it can be problem in the dependencies versions. Automatic1111 is abandoned, so maybe there were released newer versions that are not compatiable. You can try to downgrade them. Mine are torch: 2.1.2+cu121 xformers: 0.0.23.post1 (you can see them in the footer), if you know how to do it. (activate envirovment then pip install xformers="0.0.23")

i have (torch: 2.1.2+cu118) and xformers: 0.0.23.post1+cu118

**Comment by Minenblock** [comment]
> Btw, don't worry so much, 😕 the quality of video inpainting is not good, especially when comparing with modern video generation models. But I don't know do they support video inpainting. Maybe they should. I've not tested any local video models, I don't have a gpu for them, and don't like comfy ui

i can't run modern video models like WAN2.1 so i searched for an other option that dosent need that much VRAM so i came to your extension

**Comment by Minenblock** [comment]
> > i have (torch: 2.1.2+cu118) and xformers: 0.0.23.post1+cu118
> 
> Btw, does the animatediff itself work for video generation?

how can i test that?

**Comment by Minenblock** [comment]
> Find a text or video guide for animatediff in automatic1111 (txt2img tab)
> 
> Btw, what extension do you have except mine, controlnet and animatediff

ok so animateddiff crashes in txt2img aswell.

other extensions (except the 3 ones you named): sd-dynamic-prompts, sd-webui-cn-in-extras-tab, sd-webui-cn-sam-preprocessor, sd-webui-cn-sam-preprocessor, sd-webui-mobile-friendly, sd-webui-segment-anything

**Comment by Minenblock** [comment]
> They cannot crash, they are not the problem
> 
> > ok so animatediff crashes in txt2img aswell.
> 
>     * [[Bug]: RuntimeError: CUDA error: device-side assert triggered Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions. continue-revolution/sd-webui-animatediff#547](https://github.com/continue-revolution/sd-webui-animatediff/issues/547)
>       There some people solved the problem

hahaha i looked at the same page and i checked that one box and it seems to work now. i am trying it later again and if i dont comment here again in the i dont know 24 hours it is solved for me

**Comment by Minenblock** [comment]
> Hope it will work. Btw there are also my extensions "sd-webui-cn-in-extras-tab, sd-webui-cn-sam-preprocessor". :) They are popular

all right! thank you for your time and work and hopefully i dont need to comment here again :)

**Comment by Minenblock** [comment]
> They cannot crash, they are not the problem
> 
> > ok so animatediff crashes in txt2img aswell.
> 
>     * [[Bug]: RuntimeError: CUDA error: device-side assert triggered Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions. continue-revolution/sd-webui-animatediff#547](https://github.com/continue-revolution/sd-webui-animatediff/issues/547)
> 
> 
> There 1 person solved the problem
